// lib/mockAssistantsData.ts - بيانات تجريبية للاختبار
import male from "@/assets/male.png"

export const mockAssistants = [
  {
    id: "1",
    firstName: "أحمد",
    lastName: "محمد",
    email: "ahmed.mohamed.ahmed.mohamed@example.com",
    phoneNumber: "+201012345678",
    gender: 0,
    address: "القاهرة، مصر الجديدة",
    birthDate: "1995-05-15",
    profileImage: male, // يمكن وضع رابط صورة هنا
    isLocked: false,
    canManageStudents: true,
    canManageSessions: true,
    canManageAttendance: true,
    canManageExams: false,
    createdAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "2",
    firstName: "فاطمة",
    lastName: "علي",
    email: "fatima.ali@example.com",
    phoneNumber: "+201123456789",
    gender: 1,
    address: "الجيزة، المهندسين",
    birthDate: "1993-08-22",
    profileImage: male,
    isLocked: false,
    canManageStudents: true,
    canManageSessions: false,
    canManageAttendance: true,
    canManageExams: true,
    createdAt: "2024-02-10T14:20:00Z",
  },
  {
    id: "3",
    firstName: "محمود",
    lastName: "حسن",
    email: "mahmoud.hassan@example.com",
    phoneNumber: "+201234567890",
    gender: 0,
    address: "الإسكندرية، سموحة",
    birthDate: "1998-12-03",
    profileImage: male,
    isLocked: true,
    canManageStudents: false,
    canManageSessions: true,
    canManageAttendance: true,
    canManageExams: true,
    createdAt: "2024-01-20T09:15:00Z",
  },
  {
    id: "4",
    firstName: "نورا",
    lastName: "إبراهيم",
    email: "nora.ibrahim@example.com",
    phoneNumber: "+201345678901",
    gender: 1,
    address: "المنصورة، جيهان",
    birthDate: "1996-03-18",
    profileImage: male,
    isLocked: false,
    canManageStudents: true,
    canManageSessions: true,
    canManageAttendance: false,
    canManageExams: false,
    createdAt: "2024-03-05T11:45:00Z",
  },
  {
    id: "5",
    firstName: "خالد",
    lastName: "عبدالله",
    email: "khaled.abdullah@example.com",
    phoneNumber: "+201456789012",
    gender: 0,
    address: "طنطا، سيجر",
    birthDate: "1994-07-25",
    profileImage: male,
    isLocked: false,
    canManageStudents: false,
    canManageSessions: false,
    canManageAttendance: true,
    canManageExams: true,
    createdAt: "2024-02-28T16:30:00Z",
  },
  {
    id: "6",
    firstName: "سارة",
    lastName: "أحمد",
    email: "sara.ahmed@example.com",
    phoneNumber: "+201567890123",
    gender: 1,
    address: "أسيوط، الوليدية",
    birthDate: "1997-11-12",
    profileImage: male,
    isLocked: false,
    canManageStudents: true,
    canManageSessions: true,
    canManageAttendance: true,
    canManageExams: true,
    createdAt: "2024-03-15T08:00:00Z",
  },
  {
    id: "7",
    firstName: "يوسف",
    lastName: "مصطفى",
    email: "youssef.mostafa@example.com",
    phoneNumber: "+201678901234",
    gender: 0,
    address: "الفيوم، قحافة",
    birthDate: "1996-06-08",
    profileImage: male,
    isLocked: true,
    canManageStudents: true,
    canManageSessions: false,
    canManageAttendance: false,
    canManageExams: true,
    createdAt: "2024-01-05T13:30:00Z",
  },
  {
    id: "8",
    firstName: "مريم",
    lastName: "سعيد",
    email: "mariam.said@example.com",
    phoneNumber: "+201789012345",
    gender: 1,
    address: "بورسعيد، الشرق",
    birthDate: "1995-09-30",
    profileImage: male,
    isLocked: false,
    canManageStudents: false,
    canManageSessions: true,
    canManageAttendance: true,
    canManageExams: false,
    createdAt: "2024-02-20T10:15:00Z",
  },
];

// Helper function to get mock data with delay (simulate API)
export const getMockAssistants = async (teacherId: string, delay: number = 800) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(mockAssistants);
    }, delay);
  });
};

// للاستخدام في الكومبوننت:
// import { getMockAssistants } from '@/lib/mockAssistantsData';
// const data = await getMockAssistants(teacherId); 